name: Run Add-On
on: repository_dispatch

env:
  TAHOE_PASSWORD: ${{ secrets.TAHOE_PASSWORD }}

jobs:
  Run-Add-On:
    uses: MuckRock/documentcloud-addon-workflows/.github/workflows/run-addon.yml@v1
